apiVersion: v1
kind: ConfigMap
metadata:
  name: hl06-app-k8s-config
  namespace: hl06
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DBHOST: "10.60.3.9"
  DBPORT: "5433"
  DBNAME: "hl6"
  SCHEMANAME: "public"
  DB_USERNAME: "postgres"
  SERVER_TOMCAT_MAX_THREADS: "200"
  OBSERVABILITY_TICK_MS: "1000"
  OBSERVABILITY_LOG_ON_REFRESH: "true"
  OBSERVABILITY_LOG_EMPTY_SNAPSHOTS: "false"
  APP_CRASH_ENABLED: "true"
