apiVersion: v1
kind: Service
metadata:
  name: hl06-app-nodeport
  namespace: hl06
spec:
  type: NodePort
  selector:
    app: hl06-app
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 31082
