server.port=8081

spring.datasource.url=jdbc:postgresql://${DBHOST:localhost}:${DBPORT:5432}/${DBNAME:hl5}?currentSchema=${SCHEMANAME:hl5}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
server.tomcat.max-threads=${SERVER_TOMCAT_MAX_THREADS:200}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

spring.sql.init.mode=never
spring.flyway.baseline-on-migrate=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
