apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl06-app
  namespace: hl06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hl06-app
  template:
    metadata:
      labels:
        app: hl06-app
    spec:
      imagePullSecrets:
        - name: dockerhub-registry-secret
      containers:
        - name: app
          image: 10.60.3.11:8888/tospe/hl-module1:lab6
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: hl06-app-k8s-config
            - configMapRef:
                name: hl06-app-lab-kafka-config
            - secretRef:
                name: hl06-db-secret
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl06-additional
  namespace: hl06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hl06-additional
  template:
    metadata:
      labels:
        app: hl06-additional
    spec:
      imagePullSecrets:
        - name: dockerhub-registry-secret
      containers:
        - name: additional-service
          image: 10.60.3.11:8888/tospe/additional-service:ab8
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: hl06-additional-k8s-config
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
