apiVersion: v1
kind: Secret
metadata:
  name: hl06-db-secret
  namespace: hl06
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME_DB_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-registry-secret
  namespace: hl06
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "REPLACE_WITH_BASE64_DOCKER_CONFIG_JSON"
